"""
Content generation logic for processing library directories and generating LaTeX.
"""

from pathlib import Path
import utils
import code_file_handler
import latex_formatter


def process_directory(directory, depth=0, output_lines=None):
    """
    Recursively process a directory in the library.
    
    Args:
        directory: Path object of current directory
        depth: Current nesting depth (0 = section, 1 = subsection, etc.)
        output_lines: List to accumulate output lines
        
    Returns:
        List of LaTeX content lines
    """
    if output_lines is None:
        output_lines = []
    
    # Get all items in directory
    items = sorted(directory.iterdir())
    
    # Separate directories and files
    subdirs = [item for item in items if item.is_dir()]
    
    # Process files in current directory (info.tex, equation.tex, code.*, note.tex)
    has_content = False
    
    # 1. Process info.tex
    info_file = directory / 'info.tex'
    if info_file.exists():
        rel_path = info_file.as_posix()
        output_lines.append(f'\\input{{{rel_path}}}')
        has_content = True
    
    # 2. Process equation.tex
    equation_file = directory / 'equation.tex'
    if equation_file.exists():
        rel_path = equation_file.as_posix()
        output_lines.append(f'\\input{{{rel_path}}}')
        has_content = True
    
    # 3. Process code file
    code_filename, code_lang = code_file_handler.find_code_file(directory)
    if code_filename:
        code_path = directory / code_filename
        rel_path = code_path.as_posix()
        
        # Get language display name
        lang_display = code_file_handler.get_language_display_name(code_lang)
        
        # Add code header with dashed line
        header_lines = latex_formatter.format_code_header(lang_display)
        output_lines.extend(header_lines)
        
        # Add the code file
        output_lines.append(f'\\inputminted{{{code_lang}}}{{{rel_path}}}')
        has_content = True
    
    # 4. Process note.tex
    note_file = directory / 'note.tex'
    if note_file.exists():
        rel_path = note_file.as_posix()
        output_lines.append(f'\\input{{{rel_path}}}')
        has_content = True
    
    # Add spacing after content block if we had content
    if has_content:
        output_lines.append('')
    
    # Process subdirectories
    for subdir in subdirs:
        # Create section header
        section_name = utils.sanitize_name(subdir.name)
        section_cmd = utils.get_section_command(depth)
        output_lines.append(latex_formatter.format_section_header(section_name, section_cmd))
        
        # Recursively process subdirectory
        process_directory(subdir, depth + 1, output_lines)
    
    return output_lines


def generate_content_tex(library_path, output_path):
    """
    Generate content.tex file from library directory.
    
    Args:
        library_path: Path to library directory
        output_path: Path where content.tex should be written
        
    Returns:
        Number of lines written
    """
    # Process library directory
    output_lines = process_directory(library_path, depth=0)
    
    # Write to content.tex
    with output_path.open('w', encoding='utf-8') as f:
        f.write('% Auto-generated by CP Code Template Generator - DO NOT EDIT MANUALLY\n\n')
        for line in output_lines:
            f.write(line + '\n')
    
    return len(output_lines)
